global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ "prometheus:9090" ]

  - job_name: rich-domain-modeling-app
    metrics_path: /metrics
    static_configs:
      - targets: [ "app:8080" ]
