services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rich-domain-modeling-app
    environment:
      HTTP_ADDR: ":8080"
      TRACE_EXPORTER: "zipkin"
      ZIPKIN_ENDPOINT: "http://tempo:9411/api/v2/spans"
    depends_on:
      - tempo
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: rich-domain-modeling-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./deployments/observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - app

  tempo:
    image: grafana/tempo:2.6.1
    container_name: rich-domain-modeling-tempo
    command: [ "-config.file=/etc/tempo/tempo.yml" ]
    volumes:
      - ./deployments/observability/tempo/tempo.yml:/etc/tempo/tempo.yml:ro
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "9411:9411"

  loki:
    image: grafana/loki:3.2.1
    container_name: rich-domain-modeling-loki
    command: [ "-config.file=/etc/loki/loki.yml" ]
    volumes:
      - ./deployments/observability/loki/loki.yml:/etc/loki/loki.yml:ro
      - loki-data:/loki
    ports:
      - "3100:3100"

  promtail:
    image: grafana/promtail:3.2.1
    container_name: rich-domain-modeling-promtail
    command: [ "-config.file=/etc/promtail/promtail.yml" ]
    volumes:
      - ./deployments/observability/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:11.2.0
    container_name: rich-domain-modeling-grafana
    environment:
      GF_SECURITY_ADMIN_USER: "admin"
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./deployments/observability/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - loki
      - tempo

volumes:
  tempo-data:
  loki-data:
  grafana-data:
